# Generated by Django 4.1.2 on 2022-11-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
