# Generated by Django 4.1.2 on 2022-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_hospital_alter_patient_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, choices=[('HAU', 'HAU'), ('AUF', 'AUF'), ('DHVSU', 'DHVSU'), ('OLFU', 'OLFU')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.CharField(blank=True, choices=[('HAU', 'HAU'), ('AUF', 'AUF'), ('DHVSU', 'DHVSU'), ('OLFU', 'OLFU')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.CharField(blank=True, choices=[('HAU', 'HAU'), ('AUF', 'AUF'), ('DHVSU', 'DHVSU'), ('OLFU', 'OLFU')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='HospitalUser',
        ),
    ]
