# Generated by Django 4.1.2 on 2022-11-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_mobile_alter_patient_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mainadmin',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='mainadmin',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='mainadmin',
            name='status',
        ),
    ]
