# Generated by Django 4.1.2 on 2022-11-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctor_hospital_alter_patient_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
