# Generated by Django 4.1.2 on 2022-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_mainadmin_address_remove_mainadmin_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(choices=[('HAU', 'HAU'), ('AUF', 'AUF'), ('DHVSU', 'DHVSU'), ('OLFU', 'OLFU')], max_length=10),
        ),
    ]
