# Generated by Django 4.1.2 on 2022-11-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.CharField(blank=True, choices=[('HAU', 'HAU'), ('AUF', 'AUF'), ('DHVSU', 'DHVSU'), ('OLFU', 'OLFU')], default='HAU', max_length=10, null=True),
        ),
    ]
